openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/v1/payment:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: OK