openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/v1/stations:
    get:
      responses:
        '200':
          description: OK
  /api/v1/station:
    get:
      responses:
        '200':
          description: OK
  /api/v1/user/bike:
    get:
      responses:
        '200':
          description: OK